# Generated by Django 2.2.16 on 2022-07-20 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('measurement_unit', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IngredientInRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Not less than 1')], verbose_name='ingredient amount')),
            ],
            options={
                'verbose_name': 'ingredient in recipe',
                'verbose_name_plural': 'ingredients in recipes',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField(verbose_name='description')),
                ('cooking_time', models.IntegerField(verbose_name='cooking time in minutes')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Publish date')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('#0000FF', 'BLUE'), ('#FFA500', 'ORANGE'), ('#008000', 'GREEN'), ('#800080', 'PURPLE'), ('#FFFF00', 'YELLOW')], max_length=10, unique=True, verbose_name='checkbox color')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='unique slug')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
