version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  backend:
    image: andreykolesnik/api_foodgram:v2
    restart: always
    volumes:
      - backend_static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  web-migrate-import-collectstatic:
    image: andreykolesnik/api_foodgram:v2
    depends_on:
      - backend
    env_file:
      - ./.env
    command:
      - migrate-import-collectstatic
  frontend:
    image: andreykolesnik/frontend_foodgram:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - frontend
volumes:
  db:
  backend_static:
  media:
